### ISSUE TITLE
option http '-e' and '-k' canot be used together

### ISSUE THREAD

**Issue by maxadamo** [julian7/sensu-base-checks#2]
hello!   
I have found the issue shown below. 
  
This one works: 
`./sensu-base-checks http -e 5d -u https://www.google.com`

This one works: 
`./sensu-base-checks http -k -u https://www.google.com`

This one does **NOT** work:
`./sensu-base-checks http -e 5d -k -u https://www.google.com`

**Comment by maxadamo** [comment]
this is the error that it throws:

```
panic: runtime error: index out of range [0] with length 0

goroutine 19 [running]:
main.(*httpConfig).httpClient.func1(0xc000096480, 0x2, 0x2, 0x0, 0x0, 0x0, 0x2e1b213827b70a85, 0x53380d134d2c6dfc)
	/Users/js/src/github.com/julian7/sensu-base-checks/cmd/sensu-base-checks/http.go:212 +0xa4
crypto/tls.(*Conn).verifyServerCertificate(0xc000080380, 0xc000096480, 0x2, 0x2, 0x92b, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/crypto/tls/handshake_client.go:823 +0x4b3
crypto/tls.(*clientHandshakeStateTLS13).readServerCertificate(0xc000179e20, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/crypto/tls/handshake_client_tls13.go:433 +0x15e
crypto/tls.(*clientHandshakeStateTLS13).handshake(0xc000179e20, 0xc0000c2000, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/crypto/tls/handshake_client_tls13.go:85 +0x1ee
crypto/tls.(*Conn).clientHandshake(0xc000080380, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/crypto/tls/handshake_client.go:196 +0x4d9
crypto/tls.(*Conn).Handshake(0xc000080380, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/crypto/tls/conn.go:1340 +0xcc
net/http.(*persistConn).addTLS.func2(0x0, 0xc000080380, 0x0, 0xc00009c1e0)
	/usr/local/Cellar/go/1.14/libexec/src/net/http/transport.go:1453 +0x42
created by net/http.(*persistConn).addTLS
	/usr/local/Cellar/go/1.14/libexec/src/net/http/transport.go:1449 +0x1aa
```

**Comment by maxadamo** [comment]
the idea is that you may need to check the expiration of a domain, which is "self-signed", like as, Active Directory certificates are self-signed and self-generated by the DC. 
I'll try to dig in the code, but I thought it would have been easier for you because you know your code already.

**Comment by julian7** [comment]
Huh sorry, I haven't noticed your issue until just recently. It was indeed mishandled in all levels.
